### ISSUE TITLE
Unable to instantiate StatsDReporter 

### ISSUE THREAD

**Issue by arthur78** [snowplow/stream-collector#234]
Hi, I'm trying to launch the 2.6.0 version and get the following in the `snowplow_stream_collector.err`

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.RuntimeException: Unable to instantiate StatsDReporter
	at com.etsy.statsd.profiler.Agent.handleInitializationException(Agent.java:100)
	at com.etsy.statsd.profiler.Agent.instantiate(Agent.java:117)
	at com.etsy.statsd.profiler.Agent.premain(Agent.java:46)
	... 6 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.etsy.statsd.profiler.Agent.instantiate(Agent.java:115)
	... 7 more
Caused by: java.lang.NoSuchMethodError: 'void com.timgroup.statsd.NonBlockingStatsDClient.<init>(java.lang.String, java.lang.String, int)'
	at com.etsy.statsd.profiler.reporter.StatsDReporter.createClient(StatsDReporter.java:67)
	at com.etsy.statsd.profiler.reporter.StatsDReporter.createClient(StatsDReporter.java:14)
	at com.etsy.statsd.profiler.reporter.Reporter.<init>(Reporter.java:24)
	at com.etsy.statsd.profiler.reporter.StatsDReporter.<init>(StatsDReporter.java:16)
	... 12 more
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422
```

I tried both true/false for the the `enabled` key in `monitoring.metrics.statsd`.

**Comment by arthur78** [comment]
Hi, 

The issue seemed to be on our end: we were passing `statsd-jvm-profiler` as a command line parameter when starting the collector app.

Closing this.
